### ISSUE TITLE
李教授您好，我在尝试复现您的文章的时候发现您的model文件缺少EIRM模块，不知道您能不能更新下这个模块的代码呢

### ISSUE THREAD

**Issue by zsh-zzu** [qianngli/EGPNet#1]

**Comment by zsh-zzu** [comment]
RIRM is EIRM

**Comment by qianngli** [comment]
Hello! Thank you for your attention to my article. I have updated the code and included the missing EIRM module. You can download the latest version again and should be able to find the relevant module. If you have any other questions, feel free to let me know!
